### ISSUE TITLE
Avoiding duplicate aws-sdk installs / upgrading s3-upload-stream

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-upload#14]
Because aws-sdk is large it would be ideal to avoid duplicated installs of the module in the mapbox-upload tree. Currently via studio I get:

```
mapbox-studio@0.2.0 /Users/dane/projects/mbstudio
├─┬ mapbox-upload@1.1.3
│ ├── aws-sdk@1.18.0 
│ └─┬ s3-upload-stream@0.6.2
│   └── aws-sdk@2.0.15 
```

This can be worked around by upgrading aws-sdk (like #13) but I noticed that latest `s3-upload-stream` actually dropped the hard dependency on aws-sdk (https://github.com/nathanpeck/s3-upload-stream/commit/69292810f776fd8e3f433f27c71c28b4a08a8ef4#diff-a4bf1464642f4be249ac96a5bfda78d8). Any reason not to try to update to the latest s3-upload-stream?

**Comment by springmeyer** [comment]
Bump. After https://github.com/mapbox/tilemill/pull/2465 this will also lead to duplicated aws-sdk in Tilemill (and an extra 2.7 MB):

```
~/projects/tilemill[master]$ npm ls aws-sdk
tilemill@0.10.1 /Users/dane/projects/tilemill
└─┬ mapbox-upload@3.0.0
  ├── aws-sdk@2.0.29 
  └─┬ s3-upload-stream@0.6.2
    └── aws-sdk@2.0.15 

~/projects/tilemill[master]$ npm dedupe aws-sdk
npm WARN unavoidable conflict aws-sdk { '/Users/dane/projects/tilemill/node_modules/mapbox-upload/node_modules/aws-sdk': '2.0.29',
npm WARN unavoidable conflict   '/Users/dane/projects/tilemill/node_modules/mapbox-upload/node_modules/s3-upload-stream/node_modules/aws-sdk': '2.0.15' }
npm WARN unavoidable conflict Not de-duplicating
~/projects/tilemill[master]$ npm ls aws-sdk
tilemill@0.10.1 /Users/dane/projects/tilemill
└─┬ mapbox-upload@3.0.0
  ├── aws-sdk@2.0.29 
  └─┬ s3-upload-stream@0.6.2
    └── aws-sdk@2.0.15 

```

**Comment by jakepruitt** [comment]
Upgrading the dependency for s3-upload-stream to 1.0.7 involves changing the API calls, so I'll get this set up and add it to [the 3.2.0 release](https://github.com/mapbox/mapbox-upload/pull/36).

**Comment by jakepruitt** [comment]
See #36.
