### ISSUE TITLE
Granularity of shell script

### ISSUE THREAD

**Issue by rclark** [mapbox/mapbox-upload#19]
The `cli` branch starts down the path of a shell-executable script for acting on the upload API. Right now it is basically "here is my file, please upload it." I wonder if it should be expanded to [cover all the operations outlined in the upload API docs?](https://www.mapbox.com/developers/api/uploads/). 

That is to say: should it be a more granular interaction with the the upload API, allowing you to, say `mapbox-upload list` to list pending uploads, or `mapbox-upload info <uploadid>` to fetch the status of a job? Or should it remain a high-level tool that focuses on performing a single upload?

cc @willwhite @GretaCB @camillacaros

**Comment by camillacaros** [comment]
> mapbox-upload info <uploadid> to fetch the status of a job

I can see this being particularly useful for test & production renders for satellite updates. These jobs can be very heavy and time consuming & it is nice to be able to check in on status.

**Comment by mapsam** [comment]
Plans are to deprecate this repository in favor of `mapbox-cli-py`. If this feature is still desired, let's plan on opening a new ticket in that repo!

refs: https://github.com/mapbox/mapbox-cli-py/issues/83
