### ISSUE TITLE
MapboxAPI environment variable should only affect for the executable

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox-upload#25]
The mapbox-upload library [looks for a `MapboxAPI` environment variable at require-time](https://github.com/mapbox/mapbox-upload/blob/a71ad32ac1a14536a95e52b984f927b9d6ebd7ae/index.js#L30) and automatically uses the endpoint provided by the variable if set.

This opens the door for unexpected behavior if mapbox-upload is being used in the context of an application that has its own system for configuration and that application is run in an environment where the `MapboxAPI` variable is set for other reasons.

We should move the environment variable check so it is only used in the context of [bin/upload.js](https://github.com/mapbox/mapbox-upload/blob/master/bin/upload.js).

**Comment by yhahn** [comment]
Hrm, this is an api-breaking change. What issues did you run into here? For example, Mapbox Studio configures this endpoint through env var, not by modifying this directly on the module.

**Comment by willwhite** [comment]
Mapbox Studio passes in the option at call time for [styles](https://github.com/mapbox/mapbox-studio/blob/888bbd0e6c668c1a20aaadd1f962163bb2499ee2/lib/style.js#L504) and [sources](https://github.com/mapbox/mapbox-studio/blob/888bbd0e6c668c1a20aaadd1f962163bb2499ee2/lib/source.js#L721). Where else is it used in Mapbox Studio? Nothing should be depending on it and it was never meant to be used to configure the library, but I can re-roll this as a major release if necessary.

I want to both avoid the unexpected behavior described in the OP and reduce the number of ways to configure the library - there are currently three, which leads to confusion like above.
