### ISSUE TITLE
Better CLI feedback for invalid credentials

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox-upload#27]
The Mapbox API returns `Error: Not Found` for requests with invalid credentials, which is by design, but the CLI simply prints this into the terminal without any context.
- We should attempt to validate tokens better before making a request
- We should surround the error output with better context

**Comment by aaronpdennis** [comment]
This is the error I run into when I try to upload `.mbtiles` with the CLI to my Basic plan account. I used my default API access token. I'm wondering how I would validate credentials or what other issue `Error: Not Found` might be referring to.

I was also getting this error with the Node.js approach.

**Comment by aaronpdennis** [comment]
Update: I took a look at this again today and found within the Usage.txt file that 'The access token must include the "uploads:write" scope.' I never realized access tokens had different scopes, but I made a new one with the required scope and was able to successfully upload.

**Comment by lonnieljyu** [comment]
I had the same issue as aaronpdennis. Please add context to error output.

**Comment by nhenin** [comment]
how do you include the uploads:write scope ?

**Comment by aaronpdennis** [comment]
@nhenin create a new "secret" token at https://www.mapbox.com/account/apps/ and chose the scope you'll need for your token

**Comment by mapsam** [comment]
The `scopes` API endpoint is now available, which allows us to check if a particular scope is covered with a token/username. https://www.mapbox.com/api-documentation/#list-scopes

After options validation, we can do a token scope validation as well using request - we'd have to grab the username from the mapid.

```
https://api.mapbox.com/scopes/v1/{username}?access_token={token}
```

**Comment by mapsam** [comment]
Hah, in an ironic turn of events, I was able to get this working nicely only to realize you need to have the `scopes:list` scope in order to use the Scopes endpoint. I'm going to work on improving the error message at the very least.

**Comment by mapsam** [comment]
> We should surround the error output with better context

This is ready in #70 - I think validating tokens is going to be a bigger lift and since we are deprecating this in favor of `mapbox-cli-py` I think we should consider this resolved once merged.
