### ISSUE TITLE
Optionally monitor upload progress

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-upload#29]
Either as a separate API or as part of the same upload. Will help hit https://github.com/mapbox/mapbox-studio/issues/1120 and address other use cases, esp at the cli level where implementing polling yourself after running mapbox-upload is burdensome.

I'll look at this when I have time.

**Comment by mapsam** [comment]
Plans are to deprecate this repository in favor of mapbox-cli-py. If this feature is still desired, let's plan on opening a new ticket in that repo!

refs: mapbox/mapbox-cli-py#83
