### ISSUE TITLE
Setting layer Name/Description

### ISSUE THREAD

**Issue by lghamie** [mapbox/mapbox-upload#31]
Hi! I'd like to be able to set layer name/description when uploading a geojson file.

It currently just sets the mapid, but the layer name gets generated to some pretty large hexa string, and the descriptions is just "".

I tried setting it in the geoJson file, but i couldn't find a way to do it.

Is there any way to do this?

Thanks!

**Comment by mapsam** [comment]
Hi @lghamie - this might be completely moot, considering when you asked the question. You can set the `name` property now via the CLI ... `--name "your name"` flag. You cannot set the description currently.
