### ISSUE TITLE
Better error message when invalid characters used in handle

### ISSUE THREAD

**Issue by danpat** [mapbox/mapbox-upload#42]
I attempted to upload some mbtiles using the following:

```
bin/upload.js danpat.sf-foo-2015-06-18,1700 mbtiles/2015-06-18,1700.mbtiles
```

After a delay (while the file uploaded), I got:

```
Error: id must be a string with the format account.handle
```

Changing the ID to:

```
danpat.sf-foo-2015-06-18-1700
```

fixed the problem, but the error message could be a bit more helpful, and maybe caught earlier.

**Comment by mapsam** [comment]
Right now most of our validation happens server-side after the upload is sent. This isn't ideal, but splitting our validation logic between multiple libraries is going to be quite burdensome. 

With plans to deprecate this repository in favor of mapbox-cli-py, this is less of a priority.

refs: mapbox/mapbox-cli-py#83
