### ISSUE TITLE
Catch max length upload name earlier

### ISSUE THREAD

**Issue by olafveerman** [mapbox/mapbox-upload#46]
It would be great if `Error: Upload name must be 32 characters or less` would be caught before uploading a file.

**Comment by danpat** [comment]
Similar error: `Error: id must be a string with the format account.handle` which is only returned after a long wait for a big upload.

**Comment by planemad** [comment]
After waiting 30mins uploading a 800G tiff, I got `Error: Upload name contains invalid characters`

**Comment by mapsam** [comment]
This has been resolved and is now available in `mapbox-upload@4.2.4`!
