### ISSUE TITLE
Fix v4.1.0 release

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox-upload#49]
@GretaCB can you take a look at the v4.1.0 release? It looks like a tag has been pushed against [this commit](https://github.com/mapbox/mapbox-upload/commit/9dee3cc68b9bef12b896ceb98bd92326dc62b61e) but that commit is not in master (or in any branch).

**Comment by mapsam** [comment]
Despite the commit history missing the commit, the release is tied to the proper commit: https://github.com/mapbox/mapbox-upload/releases/tag/v4.1.0
