### ISSUE TITLE
Support simpler uploads with S3 POST

### ISSUE THREAD

**Issue by migurski** [mapbox/mapbox-upload#51]
I’m working with @sbma44 to update the OpenAddresses dot map periodically (https://github.com/openaddresses/machine/issues/210), and I’m running into a SNAFU with the [Mapbox upload API](https://www.mapbox.com/developers/api/uploads/).

> Mapbox provides an S3 bucket to stage your file while your upload is processed. All uploads must be staged in this bucket before being uploaded to your mapbox.com account. You can retrieve temporary credentials from this endpoint.

The credentials that come back from `/uploads/v1/<username>/credentials` include an AWS session token, but it’s not yet widely supported in all AWS client libraries. Boto, the leading library in the Python community, [does not yet support `AWS_SESSION_TOKEN`](https://github.com/boto/boto/issues/3298).

Fortunately, AWS provides an alternative that’s drastically simpler, provides identical security, and requires no client-side signing or hashing code: [Browser-Based Uploads Using POST](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingHTTPPOST.html).

> Amazon S3 supports POST, which allows your users to upload content directly to Amazon S3. POST is designed to simplify uploads, reduce upload latency, and save you money on applications where users upload data to store in Amazon S3.

As with the current flow, Mapbox would pre-sign a request and pass limited-time credentials back to a user. Unlike the current flow, those credentials would be returned as form fields that can be passed back to S3 directly, and require no signing or purpose-built client libraries. They are designed to be used in the context of a publicly-visible web page: “Your web page contains an HTTP form that contains all the information necessary for the user to upload content to Amazon S3.”

* [Additional API details from Amazon](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-authentication-HTTPPOST.html).
* [PHP implementation from ~5 years ago for reference](https://github.com/migurski/paperwalking/blob/master/site/lib/data.php#L1191) (I used this process extensively in Walking Papers).

Please consider this addition to the Mapbox API to reduce the need for AWS-specific client libraries. Cc @lyzidiamond.

**Comment by sbma44** [comment]
I've consulted with the rest of the team. The implementation you suggest makes sense and was reflected in a previous version of our upload API. Unfortunately it had its own problems, leading to the current solution.

Boto supports the current scheme with a variable rename; and boto3 should support the entire scheme properly out of the box.

**Comment by migurski** [comment]
What’s the variable rename?

**Comment by sbma44** [comment]
from the ticket in boto I believe it amounts to putting `AWS_SESSION_TOKEN` into `AWS_SECURITY_TOKEN`

**Comment by migurski** [comment]
:boom: Thank you! :boom:
