### ISSUE TITLE
Upload fails with 'Could not access url'

### ISSUE THREAD

**Issue by timiyay** [mapbox/mapbox-upload#57]
I've been attempting to upload a couple of ~500MB `.mbtiles` files using `mapbox-upload`.

When I run...
`mapbox-upload user.dataname ./data.mbtiles`

...via the CLI, the upload progress UI hangs at 0% for 1 to 10 minutes. Meanwhile, my network monitor shows upload traffic to `mapbox.s3.amazonaws.com`.

After the hang, the following happens:  

1. I get about 15 progress messages all at once, updating the progress (usually about 45-65%)
2. an error message is displayed: `Error: Could not access url`
3. the process exits

I've been getting this result reliably, with files >100MB, and on 2 different networks (home and office).

Does anyone have any tips on:  

* whether this is user error?
* strategies for preventing the error?
* strategies for retry?
* whether it's better to use `mapbox-upload`, or my own S3 upload script, for large `.mbtiles` uploads
    * I need to get some ~4GB `.mbtiles` files up on Mapbox for an upcoming project

Thanks team, I'm looking forward to using this library to take the sting out of the upload process.

**Comment by rclark** [comment]
Hi there! -- I think the best approach in this case would be to reach out to us via tech support: https://www.mapbox.com/contact/. 

That way we can first focus on making sure you get the files uploaded that you need, then track down if there are any bugs to squish in this library related to your report. Make sure to ask for @rclark in your message!

**Comment by andrewharvey** [comment]
@rclark I'm running into this issue too. Uploading via Studio UI works fine, so I think it's an issue in mapbox-upload.

**Comment by rclark** [comment]
We're actually starting to deprecate this library in favor of a single CLI tool to work across Mapbox APIs: https://github.com/mapbox/mapbox-cli-py. Could you give the upload a try with that tool, and if you continue to have trouble, file a ticket there? Thanks!

https://github.com/mapbox/mapbox-cli-py#upload

**Comment by andrewharvey** [comment]
Thanks @rclark. :+1: on deprecating this in favour of mapbox-cli-py. cli-py is working much better with the progress bar, more accurate % and time remaining nice features.
