### ISSUE TITLE
patch option format --patch=1 no longer works + --patch as a flag is ordering-dependent

### ISSUE THREAD

**Issue by dnomadb** [mapbox/mapbox-upload#60]
When running:
```
mapbox-upload --patch=1 <> <>
```
This error is returned (after upload to s3):
```
Error: patch must be a boolean
```
When changing it to a flag, it doesn't work unless passed _after_ the mapid / file args:
```
mapbox-upload --patch <> <>

error: incorrect number of arguments
```
This works:
```
mapbox-upload <> <> --patch
```

cc @GretaCB @perrygeo @rclark

**Comment by mapsam** [comment]
This has been resolved thanks to @oldpatricka in #68
