### ISSUE TITLE
improve progress reporting

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-upload#67]
When I use mapbox-upload, it jumps to reporting "100%" very fast but might sit there for a few minutes while the uplink is saturated.

It looks like the [httpUploadProgress event](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html#httpUploadProgress-event) should be used to track the upload progress.

**Comment by mapsam** [comment]
I noticed this happening recently as well. Thanks for the report @andrewharvey! Will take a look.

**Comment by andrewharvey** [comment]
@mapsam over at https://github.com/mapbox/mapbox-upload/issues/57#issuecomment-291582548 @rclark mentioned you might be deprecating this in place of mapbox-cli-py, which has a nice progress bar. So I don't know if there is much value maintaining the two tools?

**Comment by mapsam** [comment]
Indeed, though I'd like to leave mapbox-upload in a working state, rather than a buggy one. That being said, this shouldn't block deprecation at all.

**Comment by mapsam** [comment]
Hey hey @andrewharvey - I think is going to be more trouble than it's worth since we'll have to change how we construct the s3 client (from `AWS.S3` to `AWS.S3.ManagedUpload`). Considering the deprecation plan, best to chalk this one up as "wontfix".
